import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/auth/auth.interceptor';
import { API_BASE_URL } from './core/api/api.tokens';
import { environment } from '../environments/environment';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  AppstoreOutline,
  UserOutline,
  UserAddOutline,
  BellOutline,
  UpOutline,
  DownOutline,
  PlusOutline,
  LikeOutline,
  DislikeOutline,
  LikeFill,
  DislikeFill,
  MessageOutline,
  ArrowRightOutline,
  ArrowLeftOutline,
  ClockCircleOutline,
  DeleteOutline,
  EditOutline,
  PushpinOutline,
  PushpinFill,
  HeartOutline,
  HeartFill,
  SmileOutline,
  SmileFill,
  BulbOutline,
  BulbFill,
  FrownOutline,
  FrownFill,
  AlertOutline,
  AlertFill,
  MoreOutline,
  WarningOutline,
  CheckCircleOutline,
  CheckCircleFill,
  ProfileOutline,
  SettingOutline,
  WifiOutline,
  TagsOutline,
  ShareAltOutline,
  LinkOutline,
  RollbackOutline,
  SendOutline,
  MailOutline,
  TeamOutline,
} from '@ant-design/icons-angular/icons';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimations(),
    provideRouter(routes),
    {
      provide: API_BASE_URL,
      useValue: environment.apiBaseUrl,
    },
    provideHttpClient(withInterceptors([authInterceptor])),
    provideNzIcons([
      AppstoreOutline,
      UserOutline,
      UserAddOutline,
      BellOutline,
      UpOutline,
      DownOutline,
      PlusOutline,
      LikeOutline,
      DislikeOutline,
      LikeFill,
      DislikeFill,
      MessageOutline,
      ArrowRightOutline,
      ArrowLeftOutline,
      ClockCircleOutline,
      DeleteOutline,
      EditOutline,
      PushpinOutline,
      PushpinFill,
      HeartOutline,
      HeartFill,
      SmileOutline,
      SmileFill,
      BulbOutline,
      BulbFill,
      FrownOutline,
      FrownFill,
      AlertOutline,
      AlertFill,
      MoreOutline,
      WarningOutline,
      CheckCircleOutline,
      CheckCircleFill,
      ProfileOutline,
      SettingOutline,
      WifiOutline,
      TagsOutline,
      ShareAltOutline,
      LinkOutline,
      RollbackOutline,
      SendOutline,
      MailOutline,
      TeamOutline,
    ]),
  ],
};
