import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import { HttpClient, provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/auth/auth.interceptor';
import { provideTranslateService, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader, provideTranslateHttpLoader } from '@ngx-translate/http-loader';

import { API_BASE_URL } from './core/api/api.tokens';
import { environment } from '../environments/environment';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  AppstoreOutline,
  UserOutline,
  UserAddOutline,
  BellOutline,
  UpOutline,
  DownOutline,
  MedicineBoxOutline,
  FileTextOutline,
  HeartOutline,
  HeartFill,
  MoreOutline,
  PlusOutline,
  MinusOutline,
  PictureOutline,
  PictureTwoTone,
  ArrowLeftOutline,
  StarFill,
  GlobalOutline,
  UploadOutline,
  DeleteOutline,
  EyeOutline,
  FileImageOutline,
  PaperClipOutline,
  LoadingOutline,
  EnvironmentOutline,
  PhoneOutline,
  DislikeOutline,
  LikeFill,
  DislikeFill,
  MessageOutline,
  ArrowRightOutline,
  PushpinOutline,
  PushpinFill,
  SmileOutline,
  SmileFill,
  BulbOutline,
  BulbFill,
  FrownOutline,
  FrownFill,
  AlertFill,
  CheckCircleFill,
  ProfileOutline,
  SettingOutline,
  WifiOutline,
  TagsOutline,
  ShareAltOutline,
  LinkOutline,
  RollbackOutline,
  SendOutline,
  MailOutline,
  TeamOutline,
  ReloadOutline,
  CloseCircleOutline,
  ExperimentOutline,
  SolutionOutline,
  DeploymentUnitOutline,
  TagOutline,
  RetweetOutline,
  UndoOutline,
  TwitterOutline,
  WhatsAppOutline,
  RobotFill,
  FormOutline,
  HistoryOutline,
  AlertOutline,
  CheckCircleOutline,
  InfoCircleOutline,
  RightOutline,
  ToolOutline,
  SearchOutline,
  EditOutline,
  InboxOutline,
  BookOutline,
  DownloadOutline,
  PlayCircleOutline,
  LineChartOutline,
  WarningOutline,
  FileSearchOutline,
  CalendarOutline,
  ClockCircleOutline,
  RobotOutline,
  CoffeeOutline,
  StopOutline,
} from '@ant-design/icons-angular/icons';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimations(),
    provideRouter(routes),
    {
      provide: API_BASE_URL,
      useValue: environment.apiBaseUrl,
    },
    provideHttpClient(withInterceptors([authInterceptor])),
    provideNzIcons([
      AppstoreOutline,
      UserOutline,
      UserAddOutline,
      BellOutline,
      UpOutline,
      DownOutline,
      MedicineBoxOutline,
      FileTextOutline,
      HeartOutline,
      HeartFill,
      MoreOutline,
      ArrowLeftOutline,
      PictureOutline,
      PictureTwoTone,
      PlusOutline,
      MinusOutline,
      StarFill,
      GlobalOutline,
      UploadOutline,
      DeleteOutline,
      EyeOutline,
      FileImageOutline,
      PaperClipOutline,
      LoadingOutline,
      EnvironmentOutline,
      PhoneOutline,
      LikeOutline,
      DislikeOutline,
      LikeFill,
      DislikeFill,
      MessageOutline,
      ArrowRightOutline,
      ArrowLeftOutline,
      ClockCircleOutline,
      DeleteOutline,
      EditOutline,
      PushpinOutline,
      PushpinFill,
      HeartOutline,
      HeartFill,
      SmileOutline,
      SmileFill,
      BulbOutline,
      BulbFill,
      FrownOutline,
      FrownFill,
      AlertOutline,
      AlertFill,
      MoreOutline,
      WarningOutline,
      CheckCircleOutline,
      CheckCircleFill,
      ProfileOutline,
      SettingOutline,
      WifiOutline,
      TagsOutline,
      ShareAltOutline,
      LinkOutline,
      RollbackOutline,
      SendOutline,
      MailOutline,
      TeamOutline,
      ReloadOutline,
      LineChartOutline,
      CloseCircleOutline,
      ExperimentOutline,
      MedicineBoxOutline,
      SolutionOutline,
      DeploymentUnitOutline,
      TagOutline,
      RetweetOutline,
      UndoOutline,
      TwitterOutline,
      WhatsAppOutline,
      RobotOutline,
      RobotFill,
      FormOutline,
      HistoryOutline,
      PlusOutline,
      AlertOutline,
      CheckCircleOutline,
      InfoCircleOutline,
      RightOutline,
      ToolOutline,
      SearchOutline,
      EditOutline,
      DeleteOutline,
      InboxOutline,
      BookOutline,
      DownloadOutline,
      ArrowLeftOutline,
      PlayCircleOutline,
      LineChartOutline,
      MinusOutline,
      WarningOutline,
      FileSearchOutline,
      CalendarOutline,
      ClockCircleOutline,
      RobotOutline,
      CoffeeOutline,
      StopOutline,
    ]),
    provideTranslateService({
      defaultLanguage: 'en',
      loader: {
        provide: TranslateLoader,
        useClass: TranslateHttpLoader,
      },
    }),
    provideTranslateHttpLoader({
      prefix: '/i18n/',
      suffix: '.json',
    }),
  ],
};
