apiVersion: v1
kind: ConfigMap
metadata:
  name: care-config
  namespace: pidev-deployment
data:
  PORT: "8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: care
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: care
  template:
    metadata:
      labels:
        app: care
    spec:
      containers:
        - name: care
          image: notsohealthy/pidev-care:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: care-config
            - configMapRef:
                name: service-links
            - secretRef:
              name: secrets
---
apiVersion: v1
kind: Service
metadata:
  name: care
  namespace: pidev-deployment
  labels:
    app: care
spec:
  selector:
    app: care
  ports:
    - name: http
      port: 8081
      targetPort: 8081
