apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-service-config
  namespace: pidev-deployment
data:
  PORT: "8089"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-service
  template:
    metadata:
      labels:
        app: forum-service
    spec:
      containers:
        - name: forum-service
          image: notsohealthy/pidev-forum-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: forum-service-config
            - configMapRef:
                name: service-links
---
apiVersion: v1
kind: Service
metadata:
  name: forum-service
  namespace: pidev-deployment
  labels:
    app: forum-service
spec:
  selector:
    app: forum-service
  ports:
    - name: http
      port: 8089
      targetPort: 8089
