apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: pidev-deployment
data:
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: notsohealthy/pidev-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-config
            - configMapRef:
                name: service-links
            - secretRef:
              name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: pidev-deployment
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort