apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: pidev-deployment
data:
  PORT: "8082"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: notsohealthy/pidev-monitoring:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: monitoring-config
            - configMapRef:
                name: service-links
            - secretRef:
                name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: pidev-deployment
  labels:
    app: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082"
spec:
  selector:
    app: monitoring
  ports:
    - name: http
      port: 8082
      targetPort: 8082
