apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: pidev-deployment
data:
  PORT: "8090"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: notsohealthy/pidev-notifications:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: notifications-config
            - configMapRef:
                name: service-links
            - secretRef:
                name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: pidev-deployment
  labels:
    app: notifications
spec:
  selector:
    app: notifications
  ports:
    - name: http
      port: 8090
      targetPort: 8090
