apiVersion: v1
kind: ConfigMap
metadata:
  name: surveillance-and-equipment-config
  namespace: pidev-deployment
data:
  PORT: "8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveillance-and-equipment
  namespace: pidev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surveillance-and-equipment
  template:
    metadata:
      labels:
        app: surveillance-and-equipment
    spec:
      containers:
        - name: surveillance-and-equipment
          image: notsohealthy/pidev-surveillance-and-equipment:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: surveillance-and-equipment-config
            - configMapRef:
                name: service-links
            - secretRef:
              name: secrets
---
apiVersion: v1
kind: Service
metadata:
  name: surveillance-and-equipment
  namespace: pidev-deployment
  labels:
    app: surveillance-and-equipment
spec:
  selector:
    app: surveillance-and-equipment
  ports:
    - name: http
      port: 8083
      targetPort: 8083
