spring.application.name=monitoring
spring.datasource.url=${PIDEV26_DB_URL}/monitoring?sslmode=require&channel_binding=require
spring.datasource.username=${PIDEV26_DB_USERNAME}
spring.datasource.password=${PIDEV26_DB_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_LINK:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true

server.port=${PORT:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true